on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Chọn môi trường deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TAILWIND_SECRET }}
      - name: Deploy
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            ssh root@devserver "cd /var/www/laravel && ./deploy.sh develop"
          else
            ssh root@prdserver "cd /var/www/laravel && ./deploy.sh master"
          fi
