on:
  workflow_dispatch:
  #push:
    #branches:
    #  - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TAILWIND_SECRET }} # Ensure this matches the secret name in your repository settings

      - name: Deploy to server
        run: |
          ssh user@yourserver "
            cd /var/www/laravel &&
            git pull origin master &&
            composer install --no-dev --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan view:cache &&
            php artisan queue:restart
          "
